"""Golden-file regression for the pre-tail static-Eliashberg path.

The critical invariant of the bond-channels PR is that a user who does not ask
for anything new gets exactly the files they got before.  The bond-path tests
in ``tests/test_sc_bond.py`` compare two runs of the *same* (post-change)
build, which can only catch a difference between ``bond_channels`` absent and
``bond_channels = false`` -- it cannot see a change that both runs share.

This module compares against bytes produced **at commit 712b1a0**, the merge
commit this branch was cut from, i.e. genuine pre-change output.  The fixtures
live in ``tests/sc/legacy_golden/`` and were generated by the recipe in
``tests/sc/legacy_golden/generate_golden.py`` (git worktree at 712b1a0).

``chi0q`` is *loaded* from the committed ``chi0q.npz`` rather than recomputed:
``sc._calc_chi0q_internal`` is not bit-reproducible run to run (~1e-14 ULP
jitter, issue #85). Develop now shares a momentum-reversal helper across the
solvers, so the physical gap is compared at round-off tolerance while the
scalar eigenvalue output remains byte-pinned.

Tests must be run from the repository root (fixture paths are relative).
"""
import importlib.util
import os
import shutil

import numpy as np
import pytest

import hwave.sc as sc


GOLDEN_DIR = os.path.join("tests", "sc", "legacy_golden")


def _load_generator():
    """Import the golden generator so the test uses the IDENTICAL config."""
    path = os.path.join(GOLDEN_DIR, "generate_golden.py")
    spec = importlib.util.spec_from_file_location("_legacy_golden_gen", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _run_legacy(outdir, **eli_overrides):
    """Run the legacy configuration in ``outdir`` and return the raw bytes."""
    os.makedirs(outdir, exist_ok=True)
    shutil.copy(os.path.join(GOLDEN_DIR, "chi0q.npz"),
                os.path.join(outdir, "chi0q.npz"))
    input_dict = _load_generator().build_input(outdir)
    # develop now defaults to the analytic G2 tail correction. This fixture
    # pins the pre-correction 712b1a0 stream, so opt out explicitly.
    input_dict["eliashberg"]["g2_tail"] = False
    input_dict["eliashberg"].update(eli_overrides)
    sc.calc_eliashberg(input_dict)
    out = {}
    for name in ("eigenvalue.dat", "gap.dat"):
        with open(os.path.join(outdir, name), "rb") as f:
            out[name] = f.read()
    return out


def _golden(name):
    with open(os.path.join(GOLDEN_DIR, name), "rb") as f:
        return f.read()


def _assert_gap_matches_golden(got):
    np.testing.assert_allclose(
        np.loadtxt(got.splitlines()),
        np.loadtxt(_golden("gap.dat").splitlines()),
        rtol=0.0, atol=1.0e-12)


# ---------------------------------------------------------------------------
# the byte-for-byte claim against real pre-branch output
# ---------------------------------------------------------------------------

def test_default_run_matches_712b1a0_with_tail_disabled(tmp_path):
    """The explicit pre-tail mode reproduces the 712b1a0 physical result."""
    got = _run_legacy(str(tmp_path / "run"))
    assert got["eigenvalue.dat"] == _golden("eigenvalue.dat")
    _assert_gap_matches_golden(got["gap.dat"])


def test_bond_channels_false_matches_712b1a0_with_tail_disabled(tmp_path):
    """Disabling bond channels also reproduces the pre-tail physical result."""
    got = _run_legacy(str(tmp_path / "run"), bond_channels=False)
    assert got["eigenvalue.dat"] == _golden("eigenvalue.dat")
    _assert_gap_matches_golden(got["gap.dat"])


def test_legacy_eigenvalue_dat_carries_no_comment_beyond_the_header():
    """Pins WHAT the golden is, so a future regeneration cannot quietly
    launder new comment lines into the baseline."""
    text = _golden("eigenvalue.dat").decode()
    comments = [l for l in text.splitlines() if l.startswith("#")]
    assert comments == ["# Iteration eigenvalue"]


# ---------------------------------------------------------------------------
# the informative note must still appear when it carries information
# ---------------------------------------------------------------------------

def test_spectral_shift_run_does_emit_the_note(tmp_path):
    """The note is suppressed only when it says nothing; an explicit
    ``spectral_shift`` changes the MEANING of the number, so it must be
    labelled."""
    got = _run_legacy(str(tmp_path / "run"), spectral_shift="auto")
    text = got["eigenvalue.dat"].decode()
    assert "spectral_shift" in text
    assert got["eigenvalue.dat"] != _golden("eigenvalue.dat")


# ---------------------------------------------------------------------------
# _calc_g2 moved to bond_channels._g2_from_green -- prove it did not change
# ---------------------------------------------------------------------------

def _calc_g2_pre_branch(green_kw, beta):
    """Verbatim copy of ``sc._calc_g2`` as of commit 712b1a0."""
    norb = green_kw.shape[0]
    Nx, Ny, Nz, nmat = (green_kw.shape[2], green_kw.shape[3],
                        green_kw.shape[4], green_kw.shape[5])
    nvol = Nx * Ny * Nz

    green_kw_inv = np.roll(
        green_kw[:, :, ::-1, ::-1, ::-1, ::-1],
        (1, 1, 1), (2, 3, 4)
    )
    A = green_kw.reshape(norb * norb, nvol, nmat)
    B = green_kw_inv.reshape(norb * norb, nvol, nmat)
    As = np.moveaxis(A, 1, 0)
    Bs = np.moveaxis(B, 1, 0)
    G2 = np.moveaxis(As @ Bs.transpose(0, 2, 1), 0, 2)
    G2 = G2.reshape(norb, norb, norb, norb, Nx, Ny, Nz)
    return G2 / beta


@pytest.mark.parametrize("shape", [(1, 1, 4, 4, 1, 16), (2, 2, 3, 2, 2, 8)])
def test_calc_g2_is_bit_identical_to_the_pre_branch_implementation(shape):
    """``sc._calc_g2`` now delegates to
    ``bond_channels._g2_from_green``; the result must be bit-for-bit what the
    pre-branch inline implementation produced."""
    rng = np.random.default_rng(11)
    green = (rng.normal(size=shape) + 1j * rng.normal(size=shape))
    beta = 3.7
    got = sc._calc_g2(green, beta, tail=False)
    ref = _calc_g2_pre_branch(green, beta)
    assert got.dtype == ref.dtype
    assert got.shape == ref.shape
    assert np.array_equal(got, ref)


# ---------------------------------------------------------------------------
# a shifted run must say in the FILE whether its number is an eigenvalue
# ---------------------------------------------------------------------------

def test_unvalidated_shifted_run_is_labelled_in_eigenvalue_dat(tmp_path):
    """Too few iterations to validate anything: eigenvalue.dat must say the
    number is a shifted iterate-norm estimate, NOT an eigenvalue of K."""
    got = _run_legacy(str(tmp_path / "run"), spectral_shift=1.0, max_iter=2)
    text = got["eigenvalue.dat"].decode()
    assert "NOT an eigenvalue" in text
    assert "SHIFTED ITERATE-NORM ESTIMATE" in text


def test_validated_shifted_run_is_labelled_as_a_signed_eigenvalue(tmp_path):
    got = _run_legacy(str(tmp_path / "run"), spectral_shift="auto",
                      max_iter=2000)
    text = got["eigenvalue.dat"].decode()
    assert "SIGNED eigenvalue" in text
    assert "VALIDATED" in text
