[log]
  print_level = 1

[mode]
  mode = "RPA"
  # enable_spin_orbital = false
  calc_scheme = "general"

[mode.param]
  T = 0.5
  mu = 0.0
  CellShape = [32,32,1]
  SubShape = [1,1,1]
  nmat = 1024
  # Ncond = 1024
  # filling = 0.5
  # coeff_tail = 1.0

  matsubara_frequency = "all"  # default
  # matsubara_frequency = "center"
  # matsubara_frequency = 0
  # matsubara_frequency = [0,15]  # [min, max (,step)]

[file]
[file.input]
  path_to_input = "input"
  # initial = "initial.dat"
  # chi0q_init = "chi0q_full.npz"

[file.input.interaction]
  path_to_input = "input"
  Geometry = "geom.dat"
  Transfer = "transfer.dat"
  #Transfer = "transfer_spin_orbital.dat"
  CoulombIntra = "coulombintra.dat"
  CoulombInter = "coulombinter.dat"

[file.output]
  path_to_output = "output"
  chiq = "chiq"
  chi0q = "chi0q"

