[log]
  print_level = 1

[mode]
  mode = "FLEX"

[mode.param]
  T = 0.5
  CellShape = [8, 8, 1]
  SubShape = [1, 1, 1]
  Nmat = 64
  filling = 0.5
  IterationMax = 100
  Mix = 0.2
  EPS = 6

[file]
[file.input]
  path_to_input = "."

[file.input.interaction]
  path_to_input = "."
  Geometry = "geom.dat"
  Transfer = "transfer.dat"
  CoulombIntra = "coulombintra.dat"

[file.output]
  path_to_output = "output"
  chi0q = "chi0q"
  chiq = "chiq"
  sigma = "sigma"
  green = "green"
  energy = "energy.dat"
